# Generated by Django 5.1.3 on 2024-11-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
