# Generated by Django 5.1.3 on 2024-11-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
