# Generated by Django 5.1.3 on 2024-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_ratings_reviews_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='username',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
